# Generated by Django 3.2.7 on 2021-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
