# Generated by Django 3.2.7 on 2021-09-13 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20210913_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered_course',
            field=models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
    ]
