# Generated by Django 3.2.6 on 2021-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210913_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
